### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by zhimin-z** [Q-Future/Q-Bench#10]
![image](https://github.com/Q-Future/Q-Bench/assets/8592144/a7bc045e-26b4-4534-a5ca-26cec0af5858)
https://q-future.github.io/Q-Bench/leaderboards/iqa_results/

**Comment by teowu** [comment]
Please find the correct version starting with Github: [https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/iqa_results/](https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/iqa_results/). This comes from an error auto conversion.

**Comment by zhimin-z** [comment]
> Please find the correct version starting with Github: https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/iqa_results/. This comes from an error auto conversion.

![image](https://github.com/Q-Future/Q-Bench/assets/8592144/424ee64b-74f2-4f2e-a29f-10ade6120ea8)
It seems still not work...

**Comment by teowu** [comment]
Sorry, a typo. It is here: https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/IQA_outputs
