### ISSUE TITLE
The leaderboard is broken in display

### ISSUE THREAD

**Issue by zhimin-z** [Q-Future/Q-Bench#11]
![image](https://github.com/Q-Future/Q-Bench/assets/8592144/0e3d1bdb-e1b5-4528-b1a4-bb335a8b07b8)
Check https://q-future.github.io/Q-Bench/leaderboards/

**Comment by teowu** [comment]
Please find the correctly-displayed version starting with Github: [https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/](https://github.com/Q-Future/Q-Bench/tree/master/leaderboards/). This comes from an error auto conversion (the Github Page does not support Markdown-style tables).
