### ISSUE TITLE
no annotation json file for lldescribe data

### ISSUE THREAD

**Issue by yeppp27** [Q-Future/Q-Bench#12]
Hi! This work is very great. And I can't fine the json file for description annotation for lldescribe data. Thank you in advance~!

**Comment by teowu** [comment]
Hi~These LLDescribe GT Annotation are not planned to be released yet, and can only be tested via submission, as we plan to hold a competition based on this later. You may look at Q-Pathway dataset (a subset of Q-Instruct, our another project: https://huggingface.co/datasets/teowu/Q-Instruct, where `qtype` is `null`) and fetch some for validating your model.

Thank you for understanding and hope that helps.
