### ISSUE TITLE
Question about  model version.

### ISSUE THREAD

**Issue by Yangr116** [Q-Future/Q-Bench#5]
Great work!
I would like to know which llava model do you use in the experiment.
Is the base model `Vicuna-13B-v1.3`, `Vicuna-13B-v1.1`, or `Vicuna-13B-v0`?
![image](https://github.com/Q-Future/Q-Bench/assets/73805072/84ec717a-09c4-4a96-bb85-bd31ba8dfd30)
![image](https://github.com/Q-Future/Q-Bench/assets/73805072/6fbba72a-83d7-46b4-8668-5c9e6a6e4372)

**Comment by teowu** [comment]
Hi Rui!

For LLaVA-v1, we use the Vicuna-13B-v1.3, i.e. https://huggingface.co/liuhaotian/llava-v1-0719-336px-lora-vicuna-13b-v1.3.

It was the best and most popular LLaVA version when we initiated the Q-Bench project, and we also further evaluated LLaVA-v1.5 as soon as it released.

Best
Haoning
