### ISSUE TITLE
Questions about gpt-4v-vs-human.png

### ISSUE THREAD

**Issue by HenryHZY** [Q-Future/Q-Bench#7]
Hi @teowu, thanks for your great project.

I would like to ask a side question. Are your images https://github.com/Q-Future/Q-Bench/blob/master/gpt-4v-vs-human.png generated by an AI model? That is very vivid.

I'm not familiar with the diffusion model, so I would like to know what model and prompt you use. Thanks in advance:)

**Comment by teowu** [comment]
That is generated by DALLE-3. Prompts like 'GPT-4V doing an exam called "Q-Bench", in competition with a girl in glasses' may work.

**Comment by HenryHZY** [comment]
Thanks for your quick reply!
