### ISSUE TITLE
About the details of evaluating the model offline.

### ISSUE THREAD

**Issue by rubylan** [Q-Future/Q-Bench#8]
Hello authors,

Good job!
I'm wondering whether I can test my own model with q-bench offline.
I've checked the A1 annotation json file and found an unknown <concern> field (which may have some relation with the sub-type distortion/others/in-context distortion/...).
Also, the golden descriptions of A2 have not yet been released.

Thanks!

**Comment by teowu** [comment]
For A1, it has two additional fields: Type (0,1,2: corresponding to yes-no, what, how); and Concern (0,1,2,3: corresponding to distortion/others/in-context distortion/in-context others). For A1 dev, you can test it offline.

And yes, the A2 annotation is not yet released as it is kept private now. You may send an email to us to obtain the results.

Best
Haoning
